# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stackObject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('hits', models.IntegerField(default=0)),
                ('commentDepth', models.IntegerField(default=0)),
                ('fileDepth', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('hates', models.IntegerField(default=0)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedBy', models.CharField(max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
