# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_site', models.URLField(blank=True)),
                ('profile_pics', models.ImageField(blank=True, upload_to='profile_pics')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedBy', models.CharField(max_length=200, null=True)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
