# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classico_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='board',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='portfolio_site',
            new_name='profile_site',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='WebPage',
        ),
    ]
